### ISSUE TITLE
Can not retrieve dnacnn_best_B.zip

### ISSUE THREAD

**Issue by marie-michel** [bsml320/DeepFun#1]
Hello, 

I wanted to download dnacnn_best_B.zip but I get this message error : ''Error downloading object: dnacnn_best_B.zip (637baad): Smudge error: Error downloading dnacnn_best_B.zip (637baad9f187371a0a2737fc6d889e9fa34cebe0a3699b2dd8828a75d7442738): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access."

You can find attached the log associated. 

Thank you in advance. 

Marie

[20210602T171235.839638243.log](https://github.com/bsml320/DeepFun/files/6585649/20210602T171235.839638243.log)

**Comment by bsml320** [comment]
Link added:

http://bioinfo.uth.edu/deepfun/models/DeepFun_model/DeepFun_best_A.th.gz
http://bioinfo.uth.edu/deepfun/models/DeepFun_model/DeepFun_best_B.th.gz

These files are too large to be hosted by GitHub. So we put it on our lab
website.

Peilin
